OwenDeWa_CMSDEV_Labo3/src/Entity/Camps.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model\Sortable\Sortable;
use Knp\DoctrineBehaviors\Model\Timestampable\Timestampable;
use Knp\DoctrineBehaviors\Model\Translatable\Translatable;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CampsRepository")
 */
class Camps
{
    use Timestampable;
    use Translatable;
    use Sortable;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Date;

    /**
     * @ORM\Column(type="string", length=191)
     */
    private $image;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $watch;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $likes;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getWatch(): ?bool
    {
        return $this->watch;
    }

    public function setWatch(bool $watch): self
    {
        $this->watch = $watch;

        return $this;
    }

    public function getLikes(): ?int
    {
        return $this->likes;
    }

    public function setLikes(?int $likes): self
    {
        $this->likes = $likes;

        return $this;
    }

}

OwenDeWa_CMSDEV_Labo3/src/Controller/WelcomeController.php
<?php

namespace App\Controller;

use App\Entity\Camps;
use App\Entity\Reactions;
use http\Env\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class WelcomeController extends AbstractController
{
    /**
     * @Route("/{slug}", name="welcome",defaults={"slug": "nl"}, requirements= {
     *     "slug": "nl|en"
     * })
     */
    public function index($slug)
    {

        $manager = $this->getDoctrine()->getManager();
        $repository = $manager->getRepository(Camps::class);
        $camps = $repository->findBy(array(),array('id'=>'DESC'),4,0);

        $watchcamps = $repository ->findBy(array('watch' => 1));
        shuffle($watchcamps);
        return $this->render('welcome/index.html.twig', [
            'controller_name' => 'WelcomeController',
            'camps' => $camps,
            'watchcamps' => $watchcamps,
            'lang' => $slug
        ]);
    }


}

OwenDeWa_CMSDEV_Labo3/templates/welcome/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello WelcomeController!{% endblock %}

{% block container %}
    <a href="/nl">NL</a>
    <a href="/en">EN</a>
    <div class="row">

        <!-- Camp List -->

        <div class="col-sm-12 col-md-8">

            <!-- H1 Camp -->
            <a class="main-article-link" href="#">
                <div class="main-article mb-5 pb-3">
                    <img src="{{ watchcamps[0].image }}">
                </div>
            </a>

            <!-- Supporting Camps -->
            {% for camp in camps %}
                <div class="article-container my-1">
                        <a href="/{{ lang }}/detail/{{ camp.id }}">
                        <span>{{camp.translations[lang].title}}.<br> {{camp.translations[lang].quote}}.</span>
                        <img class="article-img" src="{{ camp.image }}">
                        <div class="article-title d-inline-block pl-3 align-middle">
                            <br>
                            <span class="align-left article-details"><img class="article-author-img rounded-circle" src="images/alien-profile.png"> Philippe </span>
                            <span class="pl-5 article-details float-right"> {{ camp.Date.date|date("m/d/Y") }}</span>
                        </div>
                    </a>
                </div>
            {% endfor %}


        </div>

        <!-- Right bar ad space -->


        <div class="col-sm-12 col-md-4 text-center">

            <div class="quote-space pb-2 pt-2 px-5">
                <h3 class="text-center pb-3">Getuigenissen</h3>
                <p><i class="fa fa-comment"></i> "Toen ik voor het eerst een sacoche wierp,  gooide ik nog geen twee meter ver. Maar nu gaat het al veel beter." <br>— <a href="https://www.youtube.com/watch?v=3jfNfmghZUI" target="_blank">Joost Van Hyfte</a></p>

                <p class="pt-4"><i class="fa fa-comment"></i> "Eigenlijk was ik nooit traag bij het rennen, maar altijd al een snelwandelaar geweest" <br>— <a href="https://www.youtube.com/watch?v=1z8NpmCqvZE" target="_blank">Kraantje Pappie</a></p>

                <p class="pt-4"><i class="fa fa-comment"></i> "Tijdens het jongleren, moet ik minder krabben van mijn algerie"<br>— <a href="https://www.youtube.com/watch?v=hJapJjUix8A" target="_blank">Filip Mars</a>
            </div>
        </div>
    </div>
{% endblock %}